### ISSUE TITLE
no longer working?

### ISSUE THREAD

**Issue by cnopt** [llangit/instagram-liked-posts-downloader#1]
hey man, getting some node errors when trying to run this. This is the ONLY tool like this out there, would really appreciate your help. Image attached below.

![image](https://user-images.githubusercontent.com/33091527/46634708-a53ba200-cb49-11e8-95ba-6940375d2f7c.png)

**Comment by llangit** [comment]
Hi! Thanks for letting me know.
Instagram must've made some changes. I'll look into it within the next couple of days.

**Comment by llangit** [comment]
Fixed in version 1.1
